// Package wrapper generates cache-stable Go wrapper files for discovered targets.
//
// Each wrapper exports PlanDescriptor and ShatterInvoke so that an external
// orchestrator can specify an invocation strategy (receiver construction +
// parameter source) and execute it without recompiling the target module.
// The file name embeds a discovery hash that is stable as long as the set of
// targets and constructors does not change; rebuilds are skipped when the hash
// matches an already-generated file.
package wrapper

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"go/ast"
	"go/types"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// WrapperParam describes one parameter of a wrapper target, including the
// Go type name required for code generation.
type WrapperParam struct {
	Name   string
	GoType string // concrete Go type string, e.g. "int", "*Counter", "string"
}

// WrapperTarget is an enriched description of a discovered invocation target
// with Go-level type information for code generation.
type WrapperTarget struct {
	ID            string // stable target ID, e.g. "example.com/pkg:Add"
	SymbolName    string // bare function or method name
	Kind          TargetKind
	ReceiverType  string // bare type name (without *) for method targets
	IsPointerRecv bool   // true for (*T).Method receivers
	Parameters    []WrapperParam
	HasResult     bool
	ResultGoType  string // Go type string for the first return value
	ResultCount   int    // total number of return values (0 when HasResult is false)
}

const (
	// WrapperKindZeroValue selects zero-value receiver construction.
	WrapperKindZeroValue = "zero_value"
	// WrapperKindConstructorPrefix is prepended to a constructor function
	// name to form the ReceiverKind string.
	WrapperKindConstructorPrefix = "constructor:"
)

// DiscoveryHash returns a 16-character hex prefix of the SHA-256 over the
// sorted target IDs and sorted constructor function names. The hash is fully
// determined by the discovery results so the wrapper filename is stable for
// the same set of targets and constructors.
func DiscoveryHash(targets []WrapperTarget, constructors []ConstructorCandidate) string {
	ids := make([]string, len(targets))
	for i, t := range targets {
		ids[i] = t.ID
	}
	sort.Strings(ids)

	ctors := make([]string, len(constructors))
	for i, c := range constructors {
		ctors[i] = c.FuncName + ":" + c.TargetType
	}
	sort.Strings(ctors)

	payload := strings.Join(ids, "\n") + "\n---\n" + strings.Join(ctors, "\n")
	sum := sha256.Sum256([]byte(payload))
	return hex.EncodeToString(sum[:])[:16]
}

// WrapperFilename returns the conventional filename for a wrapper given its
// discovery hash.
func WrapperFilename(hash string) string {
	return fmt.Sprintf("shatter_wrapper_%s.go", hash)
}

// GenerateWrapper produces a deterministic Go source file that exports
// PlanDescriptor and ShatterInvoke for the given targets and constructors.
// The file declares package pkgName.
//
// The output is fully determined by the inputs; calling GenerateWrapper twice
// with identical arguments produces byte-identical output.
func GenerateWrapper(
	pkgName string,
	targets []WrapperTarget,
	constructors []ConstructorCandidate,
) string {
	// Sort targets and constructors for determinism.
	sorted := make([]WrapperTarget, len(targets))
	copy(sorted, targets)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	sortedCtors := make([]ConstructorCandidate, len(constructors))
	copy(sortedCtors, constructors)
	sort.Slice(sortedCtors, func(i, j int) bool { return sortedCtors[i].FuncName < sortedCtors[j].FuncName })

	// Index constructors by target type for receiver-kind enumeration.
	ctorsByType := make(map[string][]ConstructorCandidate)
	for _, c := range sortedCtors {
		ctorsByType[c.TargetType] = append(ctorsByType[c.TargetType], c)
	}

	var b strings.Builder

	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	b.WriteString("// Code generated by Shatter. DO NOT EDIT.\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString(")\n\n")

	b.WriteString("// PlanDescriptor selects one invocation strategy for one ShatterInvoke call.\n")
	b.WriteString("type PlanDescriptor struct {\n")
	b.WriteString("\tTargetID     string `json:\"target_id\"`\n")
	b.WriteString("\tReceiverKind string `json:\"receiver_kind\"`\n")
	b.WriteString("}\n\n")

	b.WriteString("// ShatterInvoke executes the strategy in d against inputs and returns the result.\n")
	b.WriteString("func ShatterInvoke(d PlanDescriptor, inputs []json.RawMessage) (any, error) {\n")
	b.WriteString("\tswitch d.TargetID {\n")

	for _, t := range sorted {
		fmt.Fprintf(&b, "\tcase %q:\n", t.ID)
		writeTargetCase(&b, t, ctorsByType)
	}

	b.WriteString("\t}\n")
	b.WriteString("\treturn nil, fmt.Errorf(\"shatter: unknown target: %s\", d.TargetID)\n")
	b.WriteString("}\n")

	return b.String()
}

func writeTargetCase(b *strings.Builder, t WrapperTarget, ctorsByType map[string][]ConstructorCandidate) {
	if t.Kind == TargetKindFunction {
		writeParamDeserialization(b, t.Parameters, "\t\t")
		writeCall(b, t, "", "\t\t")
		return
	}

	b.WriteString("\t\tswitch d.ReceiverKind {\n")

	b.WriteString("\t\tcase \"zero_value\":\n")
	if t.IsPointerRecv {
		fmt.Fprintf(b, "\t\t\tvar _recvVal %s\n", t.ReceiverType)
		b.WriteString("\t\t\t_recv := &_recvVal\n")
	} else {
		fmt.Fprintf(b, "\t\t\tvar _recv %s\n", t.ReceiverType)
	}
	writeParamDeserialization(b, t.Parameters, "\t\t\t")
	writeCall(b, t, "_recv", "\t\t\t")

	if ctors, ok := ctorsByType[t.ReceiverType]; ok {
		for _, c := range ctors {
			recvKind := WrapperKindConstructorPrefix + c.FuncName
			fmt.Fprintf(b, "\t\tcase %q:\n", recvKind)
			if t.IsPointerRecv {
				fmt.Fprintf(b, "\t\t\t_recv := %s()\n", c.FuncName)
			} else {
				fmt.Fprintf(b, "\t\t\t_recv := *%s()\n", c.FuncName)
			}
			writeParamDeserialization(b, t.Parameters, "\t\t\t")
			writeCall(b, t, "_recv", "\t\t\t")
		}
	}

	b.WriteString("\t\t}\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"shatter: unknown receiver kind for %s: %%s\", d.ReceiverKind)\n", t.ID)
}

func writeParamDeserialization(b *strings.Builder, params []WrapperParam, indent string) {
	for i, p := range params {
		fmt.Fprintf(b, "%svar %s %s\n", indent, p.Name, p.GoType)
		fmt.Fprintf(b, "%sif %d < len(inputs) {\n", indent, i)
		fmt.Fprintf(b, "%s\tif _e := json.Unmarshal(inputs[%d], &%s); _e != nil {\n", indent, i, p.Name)
		fmt.Fprintf(b, "%s\t\treturn nil, fmt.Errorf(\"param %s: %%w\", _e)\n", indent, p.Name)
		fmt.Fprintf(b, "%s\t}\n", indent)
		fmt.Fprintf(b, "%s}\n", indent)
	}
}

func writeCall(b *strings.Builder, t WrapperTarget, recvExpr string, indent string) {
	args := make([]string, len(t.Parameters))
	for i, p := range t.Parameters {
		args[i] = p.Name
	}
	argList := strings.Join(args, ", ")

	var callExpr string
	if recvExpr == "" {
		callExpr = fmt.Sprintf("%s(%s)", t.SymbolName, argList)
	} else {
		callExpr = fmt.Sprintf("%s.%s(%s)", recvExpr, t.SymbolName, argList)
	}

	if t.HasResult {
		if t.ResultCount > 1 {
			blanks := strings.Repeat(", _", t.ResultCount-1)
			fmt.Fprintf(b, "%s_result%s := %s\n", indent, blanks, callExpr)
		} else {
			fmt.Fprintf(b, "%s_result := %s\n", indent, callExpr)
		}
		fmt.Fprintf(b, "%sreturn _result, nil\n", indent)
	} else {
		fmt.Fprintf(b, "%s%s\n", indent, callExpr)
		fmt.Fprintf(b, "%sreturn nil, nil\n", indent)
	}
}

// BuildWrapperTargets extracts a WrapperTarget for every function in pkg
// (both free functions and methods).
func BuildWrapperTargets(pkg *packages.Package) []WrapperTarget {
	if pkg == nil || pkg.TypesInfo == nil {
		return nil
	}
	var targets []WrapperTarget
	for _, file := range pkg.Syntax {
		if file == nil {
			continue
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Body == nil {
				continue
			}
			if t := buildWrapperTarget(fn, pkg); t != nil {
				targets = append(targets, *t)
			}
		}
	}
	return targets
}

func buildWrapperTarget(fn *ast.FuncDecl, pkg *packages.Package) *WrapperTarget {
	qualName := wrapperQualifiedName(fn)
	id := pkg.PkgPath + ":" + qualName

	kind := TargetKindFunction
	var recvType string
	var isPtr bool

	if fn.Recv != nil && len(fn.Recv.List) > 0 {
		kind = TargetKindMethod
		expr := fn.Recv.List[0].Type
		if star, ok := expr.(*ast.StarExpr); ok {
			isPtr = true
			if ident, ok := star.X.(*ast.Ident); ok {
				recvType = ident.Name
			}
		} else if ident, ok := expr.(*ast.Ident); ok {
			recvType = ident.Name
		}
	}

	params := extractWrapperParams(fn, pkg.TypesInfo, pkg.Name)

	hasResult := false
	var resultGoType string
	resultCount := 0
	if fn.Type.Results != nil && len(fn.Type.Results.List) > 0 {
		hasResult = true
		resultGoType = wrapperGoType(fn.Type.Results.List[0].Type, pkg.TypesInfo, pkg.Name)
		for _, field := range fn.Type.Results.List {
			if len(field.Names) == 0 {
				resultCount++
			} else {
				resultCount += len(field.Names)
			}
		}
	}

	return &WrapperTarget{
		ID:            id,
		SymbolName:    fn.Name.Name,
		Kind:          kind,
		ReceiverType:  recvType,
		IsPointerRecv: isPtr,
		Parameters:    params,
		HasResult:     hasResult,
		ResultGoType:  resultGoType,
		ResultCount:   resultCount,
	}
}

func wrapperQualifiedName(fn *ast.FuncDecl) string {
	if fn.Recv == nil || len(fn.Recv.List) == 0 {
		return fn.Name.Name
	}
	expr := fn.Recv.List[0].Type
	if star, ok := expr.(*ast.StarExpr); ok {
		if ident, ok := star.X.(*ast.Ident); ok {
			return "(*" + ident.Name + ")." + fn.Name.Name
		}
	}
	if ident, ok := expr.(*ast.Ident); ok {
		return "(" + ident.Name + ")." + fn.Name.Name
	}
	return fn.Name.Name
}

func extractWrapperParams(fn *ast.FuncDecl, info *types.Info, pkgName string) []WrapperParam {
	if fn.Type.Params == nil {
		return nil
	}
	var params []WrapperParam
	for _, field := range fn.Type.Params.List {
		goType := wrapperGoType(field.Type, info, pkgName)
		for _, name := range field.Names {
			params = append(params, WrapperParam{Name: name.Name, GoType: goType})
		}
	}
	return params
}

// wrapperGoType returns the Go type string for use in the target package.
func wrapperGoType(expr ast.Expr, info *types.Info, pkgName string) string {
	if info != nil {
		if tv, ok := info.Types[expr]; ok {
			qualifier := func(p *types.Package) string {
				if p == nil || p.Name() == pkgName {
					return ""
				}
				return p.Name()
			}
			return types.TypeString(tv.Type, qualifier)
		}
	}
	return wrapperASTTypeString(expr)
}

func wrapperASTTypeString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + wrapperASTTypeString(e.X)
	case *ast.ArrayType:
		if e.Len == nil {
			return "[]" + wrapperASTTypeString(e.Elt)
		}
		return "[...]" + wrapperASTTypeString(e.Elt)
	case *ast.MapType:
		return "map[" + wrapperASTTypeString(e.Key) + "]" + wrapperASTTypeString(e.Value)
	case *ast.SelectorExpr:
		return wrapperASTTypeString(e.X) + "." + e.Sel.Name
	case *ast.InterfaceType:
		return "any"
	default:
		return "any"
	}
}

// WriteWrapperFile writes the generated wrapper to dir/<WrapperFilename(hash)>
// and returns the file path. If the file already exists (inferred from the
// deterministic filename), the write is skipped — this is the rebuild-skip
// guarantee when the discovery hash has not changed.
//
// Returns (path, true, nil) when a new file is written, or (path, false, nil)
// when the existing file is reused.
func WriteWrapperFile(
	dir string,
	pkgName string,
	targets []WrapperTarget,
	constructors []ConstructorCandidate,
) (filePath string, fresh bool, err error) {
	hash := DiscoveryHash(targets, constructors)
	name := WrapperFilename(hash)
	path := dir + "/" + name

	if _, statErr := os.Stat(path); statErr == nil {
		return path, false, nil
	}

	src := GenerateWrapper(pkgName, targets, constructors)
	tmp := path + ".tmp"
	if writeErr := os.WriteFile(tmp, []byte(src), 0o644); writeErr != nil {
		return "", false, fmt.Errorf("wrapper: write temp %q: %w", tmp, writeErr)
	}
	if renameErr := os.Rename(tmp, path); renameErr != nil {
		_ = os.Remove(tmp)
		return "", false, fmt.Errorf("wrapper: rename to %q: %w", path, renameErr)
	}
	return path, true, nil
}
