version: '3'

tasks:
  build:
    desc: Build Rust frontend
    sources:
      - src/**/*.rs
      - Cargo.toml
      - Cargo.lock
    cmds:
      - cargo build

  test:
    desc: Run tests
    sources:
      - src/**/*.rs
      - Cargo.toml
      - Cargo.lock
    cmds:
      - |
        if command -v cargo-nextest >/dev/null 2>&1; then
          cargo test --doc
          cargo nextest run --config-file ../.config/nextest.toml
        else
          cargo test
        fi

  clippy:
    desc: Run clippy
    sources:
      - src/**/*.rs
      - Cargo.toml
      - Cargo.lock
    cmds:
      - cargo clippy -- -D warnings
