// Code generated by broad-run-corpus fixture; DO NOT EDIT.
// NoTargetReason::Generated — a file with the canonical
// "Code generated ... DO NOT EDIT" header that the Go frontend treats as
// generated.
package broadrun

type Greeting struct {
	Subject string
}

func (g Greeting) Render() string {
	return "hello " + g.Subject
}
