// Code generated by fake-generator. DO NOT EDIT.

package testdata

// MarkedGenerated is exported but should never be analyzed because the
// file carries the standard "Code generated ... DO NOT EDIT." header.
func MarkedGenerated(a, b int) int {
	return a + b
}
