#!/usr/bin/env bash
# Auto-detect GCC include path for bindgen (used by z3-sys).
#
# When only libclang1-XX is installed (without libclang-dev), clang's builtin
# headers (stdbool.h, etc.) are missing. Bindgen needs them, so we point it to
# GCC's copy via BINDGEN_EXTRA_CLANG_ARGS.
#
# This script generates .cargo/config.toml with the correct path for the
# current system. Run it once after cloning (or after changing GCC versions).
#
# Not needed inside the devcontainer (libclang-dev provides clang's headers).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_DIR="$REPO_ROOT/.cargo"
CONFIG_FILE="$CONFIG_DIR/config.toml"

# Check if libclang-dev is installed (provides clang's own headers)
if dpkg -l libclang-dev &>/dev/null 2>&1; then
    # libclang-dev is installed; no workaround needed.
    # Remove any previously generated config so it doesn't linger.
    if [ -f "$CONFIG_FILE" ]; then
        rm "$CONFIG_FILE"
        echo "Removed $CONFIG_FILE (libclang-dev provides clang headers)"
    else
        echo "No bindgen workaround needed (libclang-dev is installed)"
    fi
    exit 0
fi

# Detect GCC include path
GCC_INCLUDE="$(gcc -print-file-name=include 2>/dev/null || true)"

if [ -z "$GCC_INCLUDE" ] || [ ! -d "$GCC_INCLUDE" ]; then
    echo >&2 "Warning: could not detect GCC include path."
    echo >&2 "Install libclang-dev or GCC and re-run this script."
    exit 1
fi

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
# AUTO-GENERATED by scripts/configure-bindgen.sh — do not edit manually.
# Re-run the script if you change GCC versions.
#
# bindgen (used by z3-sys) needs clang builtin headers like stdbool.h.
# When only libclang1-XX is installed (without libclang-dev), clang's own
# resource directory is missing. This tells bindgen to fall back to GCC's
# builtin headers instead.
[env]
BINDGEN_EXTRA_CLANG_ARGS = { value = "-I${GCC_INCLUDE}", force = false }
EOF

echo "Generated $CONFIG_FILE (GCC includes: $GCC_INCLUDE)"
