package protocol

import "testing"

// str-ieuc: Go byte slices generated by Shatter must unmarshal cleanly
// before the target runs. The analyzer reports `byte` / `uint8` (and slices
// of either) using the `go_byte` complex kind so the core's generator stays
// in [0, 255] and emits a raw JSON number per element. With `int` reporting,
// the int generator emits -1, i64::MAX, etc., which json.Unmarshal rejects.

func TestAnalyzeByteSliceParamUsesGoByteComplexKind(t *testing.T) {
	results, err := AnalyzeFile(testdataPath("byte_slice.go"), "ByteSliceParam")
	if err != nil {
		t.Fatalf("AnalyzeFile: %v", err)
	}
	if len(results) != 1 {
		t.Fatalf("got %d results, want 1", len(results))
	}
	fn := results[0]
	if len(fn.Params) != 1 {
		t.Fatalf("params len = %d, want 1", len(fn.Params))
	}
	p := fn.Params[0]
	if p.Type.Kind != "array" {
		t.Fatalf("param.Type.Kind = %q, want array", p.Type.Kind)
	}
	if p.Type.Element == nil {
		t.Fatal("param.Type.Element is nil")
	}
	if p.Type.Element.Kind != "complex" {
		t.Errorf("element.Kind = %q, want complex", p.Type.Element.Kind)
	}
	if p.Type.Element.ComplexKind != "go_byte" {
		t.Errorf("element.ComplexKind = %q, want go_byte", p.Type.Element.ComplexKind)
	}
}

func TestAnalyzeUint8SliceParamUsesGoByteComplexKind(t *testing.T) {
	results, err := AnalyzeFile(testdataPath("byte_slice.go"), "Uint8SliceParam")
	if err != nil {
		t.Fatalf("AnalyzeFile: %v", err)
	}
	fn := results[0]
	elem := fn.Params[0].Type.Element
	if elem == nil || elem.Kind != "complex" || elem.ComplexKind != "go_byte" {
		t.Errorf("[]uint8 element = %+v, want complex/go_byte", elem)
	}
}

func TestAnalyzeScalarByteParamUsesGoByteComplexKind(t *testing.T) {
	results, err := AnalyzeFile(testdataPath("byte_slice.go"), "ByteParam")
	if err != nil {
		t.Fatalf("AnalyzeFile: %v", err)
	}
	p := results[0].Params[0]
	if p.Type.Kind != "complex" {
		t.Errorf("byte param Kind = %q, want complex", p.Type.Kind)
	}
	if p.Type.ComplexKind != "go_byte" {
		t.Errorf("byte param ComplexKind = %q, want go_byte", p.Type.ComplexKind)
	}
}

func TestHandshakeAdvertisesGoByteComplexType(t *testing.T) {
	h := &Handler{}
	resp := h.handleHandshake(Response{}, Request{})
	found := false
	for _, c := range resp.Capabilities {
		if c == "complex_type:go_byte" {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("handshake capabilities missing complex_type:go_byte: %v", resp.Capabilities)
	}
}
