package protocol

import (
	"fmt"
	"os"
	"strings"
	"testing"

	"pgregory.net/rapid"
)

func writeTempFile(path, body string) error {
	return os.WriteFile(path, []byte(body), 0o644)
}

// --- Filename-based detection ---

func TestHasGeneratedFilename_KnownPatterns(t *testing.T) {
	cases := []struct {
		path string
		want bool
	}{
		// Positive: known generated patterns.
		{"foo.pb.go", true},
		{"path/to/widget.pb.go", true},
		{"service.pb.gw.go", true},
		{"thing_gen.go", true},
		{"path/to/x_gen.go", true},
		{"zz_generated.go", true},
		{"zz_generated_deepcopy.go", true},
		{"zz_generated.deepcopy.go", true},

		// Negative: non-generated filenames.
		{"foo.go", false},
		{"foo_test.go", false},
		{"helper.go", false},
		{"genuine.go", false}, // does not end in _gen.go
		{"pbgo.go", false},    // does not end in .pb.go
		{"foo.txt", false},    // not a .go file
		{"", false},
	}
	for _, c := range cases {
		got := hasGeneratedFilename(c.path)
		if got != c.want {
			t.Errorf("hasGeneratedFilename(%q) = %v, want %v", c.path, got, c.want)
		}
	}
}

// PBT: random base names that are not in any of the known generated patterns
// must always be classified non-generated.
func TestHasGeneratedFilename_RandomNonGenerated(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		alphaLowercase := "abcdefghijklmnopqrstuvwxyz"
		stem := rapid.StringOf(rapid.SampledFrom([]rune(alphaLowercase))).
			Filter(func(s string) bool { return s != "" }).
			Draw(t, "stem")

		path := stem + ".go"
		// Construct a name guaranteed to miss every pattern.
		if strings.HasSuffix(path, ".pb.go") ||
			strings.HasSuffix(path, ".pb.gw.go") ||
			strings.HasSuffix(path, "_gen.go") ||
			strings.HasPrefix(path, "zz_generated") {
			t.Skip("randomly drew a generated-looking name; skipping")
		}
		if hasGeneratedFilename(path) {
			t.Errorf("hasGeneratedFilename(%q) = true, want false", path)
		}
	})
}

// PBT: any randomly chosen stem combined with a known generated suffix or
// prefix must be classified generated.
func TestHasGeneratedFilename_RandomGenerated(t *testing.T) {
	patterns := []func(string) string{
		func(stem string) string { return stem + ".pb.go" },
		func(stem string) string { return stem + ".pb.gw.go" },
		func(stem string) string { return stem + "_gen.go" },
		func(stem string) string { return "zz_generated" + stem + ".go" },
		func(stem string) string { return "zz_generated_" + stem + ".go" },
	}
	rapid.Check(t, func(t *rapid.T) {
		alphaLowercase := "abcdefghijklmnopqrstuvwxyz"
		stem := rapid.StringOf(rapid.SampledFrom([]rune(alphaLowercase))).
			Filter(func(s string) bool { return s != "" }).
			Draw(t, "stem")
		idx := rapid.IntRange(0, len(patterns)-1).Draw(t, "patternIndex")

		path := patterns[idx](stem)
		if !hasGeneratedFilename(path) {
			t.Errorf("hasGeneratedFilename(%q) = false, want true", path)
		}
	})
}

// --- Header-based detection ---

func TestHasGeneratedHeader_PositiveCases(t *testing.T) {
	cases := []string{
		// Canonical protoc-gen-go header.
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n",
		// stringer.
		"// Code generated by \"stringer -type=Pill\"; DO NOT EDIT.\npackage foo\n",
		// Header preceded by leading comment block (allowed: must appear
		// before first non-comment, non-blank line).
		"// Copyright 2025 Acme.\n// Code generated by mockgen. DO NOT EDIT.\npackage foo\n",
		// Header preceded by blank lines.
		"\n\n// Code generated by genny. DO NOT EDIT.\npackage foo\n",
	}
	for _, src := range cases {
		if !hasGeneratedHeader([]byte(src)) {
			t.Errorf("hasGeneratedHeader = false, want true for source:\n%s", src)
		}
	}
}

func TestHasGeneratedHeader_NegativeCases(t *testing.T) {
	cases := []string{
		// No header at all.
		"package foo\n",
		// Header-like comment but missing the trailing 'DO NOT EDIT.' marker.
		"// Code generated by foo.\npackage foo\n",
		// Header that appears after a non-comment line is ignored per the
		// Go convention.
		"package foo\n\n// Code generated by latebird. DO NOT EDIT.\n",
		// Doc string mentioning generated code, but not on its own comment line.
		"// This file references the phrase Code generated DO NOT EDIT but is\n" +
			"// not itself generated.\npackage foo\n",
	}
	for _, src := range cases {
		if hasGeneratedHeader([]byte(src)) {
			t.Errorf("hasGeneratedHeader = true, want false for source:\n%s", src)
		}
	}
}

// --- Combined detection ---

func TestIsGeneratedFile_HeaderOnly(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/handcrafted_name.go"
	body := "// Code generated by widget. DO NOT EDIT.\npackage foo\n"
	if err := writeTempFile(path, body); err != nil {
		t.Fatalf("write: %v", err)
	}
	if !isGeneratedFile(path) {
		t.Errorf("isGeneratedFile(%q) = false, want true (header marks it generated)", path)
	}
}

func TestIsGeneratedFile_FilenameOnly(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/widget.pb.go"
	body := "package foo\n" // no header
	if err := writeTempFile(path, body); err != nil {
		t.Fatalf("write: %v", err)
	}
	if !isGeneratedFile(path) {
		t.Errorf("isGeneratedFile(%q) = false, want true (filename marks it generated)", path)
	}
}

func TestIsGeneratedFile_Neither(t *testing.T) {
	dir := t.TempDir()
	path := dir + "/handcrafted.go"
	body := "package foo\n\nfunc Add(a, b int) int { return a + b }\n"
	if err := writeTempFile(path, body); err != nil {
		t.Fatalf("write: %v", err)
	}
	if isGeneratedFile(path) {
		t.Errorf("isGeneratedFile(%q) = true, want false", path)
	}
}

func TestIsGeneratedFile_MissingFile(t *testing.T) {
	// Non-existent file with non-generated name: must not panic and must
	// return false (let downstream stat errors surface to the caller).
	if isGeneratedFile("/nonexistent/path/handcrafted.go") {
		t.Error("isGeneratedFile of nonexistent non-generated file = true, want false")
	}
	// Non-existent file with generated filename: filename check alone marks
	// it generated; we should still report true without reading the file.
	if !isGeneratedFile("/nonexistent/path/widget.pb.go") {
		t.Error("isGeneratedFile of nonexistent .pb.go file = false, want true")
	}
}

// --- Handler integration: each command rejects generated files. ---

func TestAnalyzeGeneratedFileReturnsNotSupported(t *testing.T) {
	for _, name := range []string{"generated_by_header.go", "widget.pb.go"} {
		t.Run(name, func(t *testing.T) {
			file := testdataPath(name)
			req := reqJSON(2, "analyze", fmt.Sprintf(`"file":"%s"`, file))
			resp := sendRecv(t, req)
			if resp.Status != "error" {
				t.Errorf("status = %q, want error", resp.Status)
			}
			if resp.Code != ErrNotSupported {
				t.Errorf("code = %q, want %s", resp.Code, ErrNotSupported)
			}
			if !strings.Contains(resp.Message, "generated") {
				t.Errorf("message should mention generated, got %q", resp.Message)
			}
		})
	}
}

func TestInstrumentGeneratedFileReturnsNotSupported(t *testing.T) {
	file := testdataPath("widget.pb.go")
	req := reqJSON(2, "instrument", fmt.Sprintf(`"file":"%s"`, file))
	resp := sendRecv(t, req)
	if resp.Status != "error" {
		t.Errorf("status = %q, want error", resp.Status)
	}
	if resp.Code != ErrNotSupported {
		t.Errorf("code = %q, want %s", resp.Code, ErrNotSupported)
	}
}

func TestPrepareGeneratedFileReturnsNotSupported(t *testing.T) {
	file := testdataPath("widget.pb.go")
	fn := "Foo"
	req := reqJSON(2, "prepare", fmt.Sprintf(`"file":"%s","function":"%s"`, file, fn))
	resp := sendRecv(t, req)
	if resp.Status != "error" {
		t.Errorf("status = %q, want error", resp.Status)
	}
	if resp.Code != ErrNotSupported {
		t.Errorf("code = %q, want %s", resp.Code, ErrNotSupported)
	}
}

func TestExecuteGeneratedFileReturnsNotSupported(t *testing.T) {
	file := testdataPath("widget.pb.go")
	fn := "Foo"
	req := reqJSON(2, "execute", fmt.Sprintf(`"file":"%s","function":"%s","inputs":[]`, file, fn))
	resp := sendRecv(t, req)
	if resp.Status != "error" {
		t.Errorf("status = %q, want error", resp.Status)
	}
	if resp.Code != ErrNotSupported {
		t.Errorf("code = %q, want %s", resp.Code, ErrNotSupported)
	}
}
