package protocol

import (
	"bufio"
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Generated-code skipping
//
// Shatter does not generate tests for code that is itself generated by a
// codegen tool (protoc, stringer, mockgen, controller-gen, etc.). Generated
// files are routinely overwritten on regeneration, so any harness produced
// from them is throw-away work; analyzing them also wastes cycles on
// machine-emitted boilerplate that rarely encodes interesting domain logic.
// See docs/go-frontend-scope-limits.md (Generated code) and beads str-1giz.
//
// Two detection mechanisms run independently, and a positive match from
// either is sufficient:
//
//  1. The standard "Code generated ... DO NOT EDIT." header per
//     https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source —
//     the comment must appear before the first non-comment, non-blank line.
//  2. Well-known generated-code filename patterns (*.pb.go, *.pb.gw.go,
//     *_gen.go, zz_generated*.go).

// generatedHeaderPattern matches the canonical "Code generated ... DO NOT
// EDIT." marker on a single comment line. Per the Go convention the line
// must be a `//` comment and the marker must occupy the entire line.
var generatedHeaderPattern = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// generatedHeaderScanLimit caps how many bytes of the file we read when
// looking for the generated header. Real generated headers always sit at
// the top of the file with at most a copyright preamble before them, so a
// few kilobytes is more than enough to detect them without paying the cost
// of reading machine-emitted files that can be megabytes long.
const generatedHeaderScanLimit = 8 * 1024

// isGeneratedFile reports whether path refers to a Go file that should be
// skipped from analysis because it is generated. Filename-pattern matching
// happens first because it does not require touching the filesystem; if
// the filename is inconclusive the file's leading bytes are scanned for
// the standard generated-header comment.
func isGeneratedFile(path string) bool {
	if hasGeneratedFilename(path) {
		return true
	}
	header, err := readFileHeader(path, generatedHeaderScanLimit)
	if err != nil {
		// If the file cannot be read, defer the error to the caller's
		// own os.Stat / read step. We never mark an unreadable file as
		// generated based on a read failure alone.
		return false
	}
	return hasGeneratedHeader(header)
}

// hasGeneratedFilename reports whether path's base name matches a
// well-known codegen pattern. The canonical patterns recognized are:
//
//	*.pb.go           — protoc-gen-go output
//	*.pb.gw.go        — grpc-gateway output
//	*_gen.go          — generic codegen suffix (genny, etc.)
//	zz_generated*.go  — controller-gen, kubebuilder, kubernetes deepcopy
func hasGeneratedFilename(path string) bool {
	base := filepath.Base(path)
	if base == "" || !strings.HasSuffix(base, ".go") {
		return false
	}
	switch {
	case strings.HasSuffix(base, ".pb.go"):
		return true
	case strings.HasSuffix(base, ".pb.gw.go"):
		return true
	case strings.HasSuffix(base, "_gen.go"):
		return true
	case strings.HasPrefix(base, "zz_generated"):
		return true
	}
	return false
}

// hasGeneratedHeader reports whether content carries the standard "Code
// generated ... DO NOT EDIT." marker. Per the Go convention the marker
// must appear on its own `//` comment line before the first non-comment,
// non-blank line of the file.
func hasGeneratedHeader(content []byte) bool {
	scanner := bufio.NewScanner(bytes.NewReader(content))
	// Generated headers are short; the default 64 KiB token size is more
	// than enough.
	for scanner.Scan() {
		line := strings.TrimRight(scanner.Text(), "\r")
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if !strings.HasPrefix(trimmed, "//") {
			// First non-comment, non-blank line: per the Go convention,
			// any later "Code generated ... DO NOT EDIT." line does not
			// count.
			return false
		}
		if generatedHeaderPattern.MatchString(trimmed) {
			return true
		}
	}
	return false
}

// readFileHeader returns at most limit bytes from the start of path. EOF
// before limit is not an error.
func readFileHeader(path string, limit int) ([]byte, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	buffer := make([]byte, limit)
	bytesRead, err := file.Read(buffer)
	if err != nil && bytesRead == 0 {
		return nil, err
	}
	return buffer[:bytesRead], nil
}
