// Code generated by scripts/protocol-codegen.py; DO NOT EDIT.
// Source of truth: protocol/registry.yaml
// Regenerate with: python3 scripts/protocol-codegen.py --write
//
// This file is the only place command, response-status, error-code,
// setup-level, generator-kind, and branch-type slices are defined
// in shatter-go. Hand-written typed constants in constants.go and
// types.go are reconciled against these slices by
// generated_enums_test.go so manual drift between the registry and
// the Go frontend is caught at test time.

package protocol

// ProtocolVersion is the protocol version negotiated between core and
// the Go frontend.
const ProtocolVersion = "0.1.0"

// AllCommands is every command core may send to a frontend (full registry surface;
// individual frontends may decline unsupported commands at runtime).
var AllCommands = []string{
	"analyze",
	"execute",
	"generate",
	"get_invocation_plan",
	"handshake",
	"instrument",
	"prepare",
	"setup",
	"shutdown",
	"teardown",
}

// AllResponseStatuses is every response status a frontend may emit, including the
// universal "error" status.
var AllResponseStatuses = []string{
	"analyze",
	"error",
	"execute",
	"generate",
	"handshake",
	"instrument",
	"invocation_plan",
	"prepare",
	"setup",
	"shutdown_ack",
	"teardown_ack",
}

// AllErrorCodes is the canonical error codes. Frozen list mirrored from
// registry.yaml.
var AllErrorCodes = []string{
	"compilation_error",
	"execution_crash",
	"execution_timeout",
	"file_not_found",
	"function_not_found",
	"instrumentation_failed",
	"internal_error",
	"invalid_request",
	"not_supported",
	"parse_error",
	"preflight_failed",
	"version_mismatch",
}

// AllSetupLevels is the setup/teardown lifecycle scopes.
var AllSetupLevels = []string{
	"execution",
	"file",
	"function",
	"session",
}

// AllGeneratorKinds is the generator-kind values (type vs parameter name).
var AllGeneratorKinds = []string{
	"param_name",
	"type_name",
}

// AllBranchTypes is the source-level constructs that produce branch decisions.
var AllBranchTypes = []string{
	"else_if",
	"for",
	"if",
	"logical_and",
	"logical_or",
	"select",
	"switch",
	"ternary",
	"while",
}
