package launcher_test

import (
	"strings"
	"testing"

	"github.com/shatter-dev/shatter/shatter-go/launcher"
)

func TestGenerateLauncherMainIsDeterministic(t *testing.T) {
	importPath := "example.com/targets"
	first := launcher.GenerateLauncherMain(importPath)
	second := launcher.GenerateLauncherMain(importPath)
	if first != second {
		t.Error("GenerateLauncherMain is not deterministic")
	}
}

func TestGenerateLauncherMainHeader(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	if !strings.Contains(src, "// Code generated by Shatter. DO NOT EDIT.") {
		t.Error("missing generated-file header")
	}
	if !strings.HasPrefix(strings.TrimPrefix(src, "// Code generated by Shatter. DO NOT EDIT.\n"), "package main") {
		t.Error("first non-comment line must be 'package main'")
	}
}

func TestGenerateLauncherMainImportsTargetPackage(t *testing.T) {
	importPath := "example.com/mypkg"
	src := launcher.GenerateLauncherMain(importPath)
	if !strings.Contains(src, `"example.com/mypkg"`) {
		t.Errorf("generated source missing import %q\nsource:\n%s", importPath, src)
	}
}

func TestGenerateLauncherMainContainsWireTypes(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	for _, want := range []string{
		"launcherRequest",
		"launcherResponse",
		"target.PlanDescriptor",
		"target.ShatterInvoke",
		"ReturnValue",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestGenerateLauncherMainContainsRunLoop(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	for _, want := range []string{
		"bufio.NewScanner",
		"sc.Scan()",
		"json.Unmarshal",
		"enc.Encode",
		"os.Exit(1)",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestGenerateLauncherMainDiffersByImportPath(t *testing.T) {
	a := launcher.GenerateLauncherMain("example.com/pkg-a")
	b := launcher.GenerateLauncherMain("example.com/pkg-b")
	if a == b {
		t.Error("different import paths should produce different sources")
	}
}

func TestBuildOptionsValidation(t *testing.T) {
	cases := []struct {
		name string
		opts launcher.BuildOptions
		want string
	}{
		{
			name: "missing hash",
			opts: launcher.BuildOptions{TargetModulePath: "x", TargetModuleDir: "/x", TargetImportPath: "x"},
			want: "DiscoveryHash",
		},
		{
			name: "missing module path",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModuleDir: "/x", TargetImportPath: "x"},
			want: "TargetModulePath",
		},
		{
			name: "missing module dir",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModulePath: "x", TargetImportPath: "x"},
			want: "TargetModuleDir",
		},
		{
			name: "missing import path",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModulePath: "x", TargetModuleDir: "/x"},
			want: "TargetImportPath",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, _, err := launcher.BuildLauncher(tc.opts)
			if err == nil {
				t.Fatal("expected error, got nil")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q missing %q", err.Error(), tc.want)
			}
		})
	}
}
