package launcher_test

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"testing"

	"github.com/shatter-dev/shatter/shatter-go/launcher"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
)

func TestGenerateLauncherMainIsDeterministic(t *testing.T) {
	importPath := "example.com/targets"
	first := launcher.GenerateLauncherMain(importPath)
	second := launcher.GenerateLauncherMain(importPath)
	if first != second {
		t.Error("GenerateLauncherMain is not deterministic")
	}
}

func TestGenerateLauncherMainHeader(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	if !strings.Contains(src, "// Code generated by Shatter. DO NOT EDIT.") {
		t.Error("missing generated-file header")
	}
	if !strings.HasPrefix(strings.TrimPrefix(src, "// Code generated by Shatter. DO NOT EDIT.\n"), "package main") {
		t.Error("first non-comment line must be 'package main'")
	}
}

func TestGenerateLauncherMainImportsTargetPackage(t *testing.T) {
	importPath := "example.com/mypkg"
	src := launcher.GenerateLauncherMain(importPath)
	if !strings.Contains(src, `"example.com/mypkg"`) {
		t.Errorf("generated source missing import %q\nsource:\n%s", importPath, src)
	}
}

func TestGenerateLauncherMainContainsWireTypes(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	for _, want := range []string{
		"launcherRequest",
		"launcherResponse",
		"target.PlanDescriptor",
		"target.ShatterInvoke",
		"ReturnValue",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestGenerateLauncherMainContainsRunLoop(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	for _, want := range []string{
		"bufio.NewScanner",
		"sc.Scan()",
		"json.Unmarshal",
		"enc.Encode",
		"os.Exit(1)",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestGenerateLauncherMainDiffersByImportPath(t *testing.T) {
	a := launcher.GenerateLauncherMain("example.com/pkg-a")
	b := launcher.GenerateLauncherMain("example.com/pkg-b")
	if a == b {
		t.Error("different import paths should produce different sources")
	}
}

func TestBuildOptionsValidation(t *testing.T) {
	cases := []struct {
		name string
		opts launcher.BuildOptions
		want string
	}{
		{
			name: "missing hash",
			opts: launcher.BuildOptions{TargetModulePath: "x", TargetModuleDir: "/x", TargetImportPath: "x"},
			want: "DiscoveryHash",
		},
		{
			name: "missing module path",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModuleDir: "/x", TargetImportPath: "x"},
			want: "TargetModulePath",
		},
		{
			name: "missing module dir",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModulePath: "x", TargetImportPath: "x"},
			want: "TargetModuleDir",
		},
		{
			name: "missing import path",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModulePath: "x", TargetModuleDir: "/x"},
			want: "TargetImportPath",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, _, err := launcher.BuildLauncher(tc.opts)
			if err == nil {
				t.Fatal("expected error, got nil")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q missing %q", err.Error(), tc.want)
			}
		})
	}
}

func TestBuildLauncherConcurrentCallsShareSingleBuild(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("fake go script uses POSIX shell")
	}

	fakeBinDir := t.TempDir()
	countDir := t.TempDir()
	fakeGo := filepath.Join(fakeBinDir, "go")
	fakeGoScript := `#!/bin/sh
set -eu
out=""
while [ "$#" -gt 0 ]; do
	if [ "$1" = "-o" ]; then
		shift
		out="$1"
	fi
	shift || true
done
if [ -z "$out" ]; then
	exit 0
fi
touch "$SHATTER_FAKE_GO_COUNT_DIR/invocation-$$"
sleep 0.2
mkdir -p "$(dirname "$out")"
printf '#!/bin/sh\nexit 0\n' > "$out"
chmod +x "$out"
`
	if err := os.WriteFile(fakeGo, []byte(fakeGoScript), 0o755); err != nil {
		t.Fatalf("write fake go: %v", err)
	}
	t.Setenv("PATH", fakeBinDir+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("SHATTER_FAKE_GO_COUNT_DIR", countDir)

	targetModuleDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(targetModuleDir, "go.mod"), []byte("module example.com/targets\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatalf("write target go.mod: %v", err)
	}

	opts := launcher.BuildOptions{
		TargetModulePath: "example.com/targets",
		TargetModuleDir:  targetModuleDir,
		TargetImportPath: "example.com/targets",
		DiscoveryHash:    "same-discovery-hash",
		GeneratedDir:     filepath.Join(t.TempDir(), "generated"),
		BinariesDir:      filepath.Join(t.TempDir(), "binaries"),
	}

	const workers = 8
	start := make(chan struct{})
	var wg sync.WaitGroup
	wg.Add(workers)
	freshResults := make(chan bool, workers)
	errs := make(chan error, workers)

	for range workers {
		go func() {
			defer wg.Done()
			<-start
			_, fresh, err := launcher.BuildLauncher(opts)
			if err != nil {
				errs <- err
				return
			}
			freshResults <- fresh
		}()
	}

	close(start)
	wg.Wait()
	close(errs)
	close(freshResults)

	for err := range errs {
		t.Errorf("BuildLauncher returned error: %v", err)
	}
	if t.Failed() {
		return
	}

	markers, err := os.ReadDir(countDir)
	if err != nil {
		t.Fatalf("read fake go markers: %v", err)
	}
	if len(markers) != 1 {
		t.Fatalf("go build invocations = %d, want 1", len(markers))
	}

	freshCount := 0
	for fresh := range freshResults {
		if fresh {
			freshCount++
		}
	}
	if freshCount != 1 {
		t.Fatalf("fresh builds = %d, want 1", freshCount)
	}
}

// TestBuildLauncherAtomicWriteAgainstSlowBuild reproduces str-0cui: when go
// build creates the output file non-atomically (e.g. via copy-fallback on a
// cross-filesystem GOCACHE), a concurrent BuildLauncher call can observe the
// partial file via its pre-lock cache stat and return a not-yet-complete path
// to the caller. The caller then execs a partial / busy binary and trips
// `text file busy` or other startup failures.
//
// We simulate the non-atomic write with a fake `go` that creates the output
// path empty, sleeps, and only later writes a real executable script. Any
// path returned by BuildLauncher must point at a fully written, executable
// file regardless of when in the producer's lifecycle the caller arrived.
func TestBuildLauncherAtomicWriteAgainstSlowBuild(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("fake go script uses POSIX shell")
	}

	fakeBinDir := t.TempDir()
	fakeGo := filepath.Join(fakeBinDir, "go")
	fakeGoScript := `#!/bin/sh
set -eu
out=""
while [ "$#" -gt 0 ]; do
	if [ "$1" = "-o" ]; then
		shift
		out="$1"
	fi
	shift || true
done
if [ -z "$out" ]; then
	exit 0
fi
mkdir -p "$(dirname "$out")"
# Phase 1: create output path empty and executable, simulating go's
# non-atomic copy-fallback that opens O_CREATE|O_WRONLY|O_TRUNC.
: > "$out"
chmod +x "$out"
# Phase 2: simulate the body of the write taking time.
sleep 0.3
# Phase 3: write the real contents.
printf '#!/bin/sh\nexit 0\n' > "$out"
chmod +x "$out"
`
	if err := os.WriteFile(fakeGo, []byte(fakeGoScript), 0o755); err != nil {
		t.Fatalf("write fake go: %v", err)
	}
	t.Setenv("PATH", fakeBinDir+string(os.PathListSeparator)+os.Getenv("PATH"))

	targetModuleDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(targetModuleDir, "go.mod"), []byte("module example.com/targets\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatalf("write target go.mod: %v", err)
	}

	opts := launcher.BuildOptions{
		TargetModulePath: "example.com/targets",
		TargetModuleDir:  targetModuleDir,
		TargetImportPath: "example.com/targets",
		DiscoveryHash:    "atomic-race-hash",
		GeneratedDir:     filepath.Join(t.TempDir(), "generated"),
		BinariesDir:      filepath.Join(t.TempDir(), "binaries"),
	}

	const workers = 8
	start := make(chan struct{})
	var wg sync.WaitGroup
	wg.Add(workers)
	type workerResult struct {
		path        string
		size        int64
		statErr     error
		err         error
	}
	results := make(chan workerResult, workers)

	for range workers {
		go func() {
			defer wg.Done()
			<-start
			path, _, err := launcher.BuildLauncher(opts)
			res := workerResult{path: path, err: err}
			if err == nil {
				info, statErr := os.Stat(path)
				if statErr != nil {
					res.statErr = statErr
				} else {
					res.size = info.Size()
				}
			}
			results <- res
		}()
	}

	close(start)
	wg.Wait()
	close(results)

	emptyObserved := 0
	for r := range results {
		if r.err != nil {
			t.Errorf("BuildLauncher returned error: %v", r.err)
			continue
		}
		if r.statErr != nil {
			t.Errorf("stat returned binary %q: %v", r.path, r.statErr)
			continue
		}
		t.Logf("worker returned path=%q size=%d (observed immediately on return)", r.path, r.size)
		if r.size == 0 {
			emptyObserved++
		}
	}
	if emptyObserved > 0 {
		t.Errorf("%d workers received an empty (partial) binary from BuildLauncher: callers would exec a partially-written file (text file busy / startup failure)", emptyObserved)
	}
}

// str-jeen.61: launcher go.mod must use the target module's go version.

func TestReadTargetGoModVersion(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/tgt\n\ngo 1.26.3\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	goVersion, _ := launcher.ReadTargetGoMod(dir)
	if goVersion != "1.26.3" {
		t.Errorf("go version = %q, want %q", goVersion, "1.26.3")
	}
}

func TestReadTargetGoModMissingFallback(t *testing.T) {
	dir := t.TempDir() // no go.mod
	goVersion, replaces := launcher.ReadTargetGoMod(dir)
	if goVersion != "" {
		t.Errorf("expected empty version, got %q", goVersion)
	}
	if replaces != nil {
		t.Errorf("expected nil replaces, got %v", replaces)
	}
}

func TestBuildLauncherGoModUsesTargetVersion(t *testing.T) {
	got := launcher.BuildLauncherGoModForTest(
		"launcher/mod", "example.com/tgt", "/tmp/tgt",
		false, "",
		"1.26.3", nil,
	)
	if !strings.Contains(got, "go 1.26.3") {
		t.Errorf("expected 'go 1.26.3' in go.mod, got:\n%s", got)
	}
}

func TestBuildLauncherGoModFallsBackToDefault(t *testing.T) {
	got := launcher.BuildLauncherGoModForTest(
		"launcher/mod", "example.com/tgt", "/tmp/tgt",
		false, "",
		"", nil, // empty version triggers fallback
	)
	if !strings.Contains(got, "go 1.23.0") {
		t.Errorf("expected fallback 'go 1.23.0' in go.mod, got:\n%s", got)
	}
}

// str-jeen.75: local replace directives from target go.mod must be propagated.

func TestBuildLauncherGoModPropagatesLocalReplace(t *testing.T) {
	replaces := []*modfile.Replace{
		{
			Old: module.Version{Path: "github.com/foo/bar"},
			New: module.Version{Path: "/abs/path/to/api"},
		},
	}
	got := launcher.BuildLauncherGoModForTest(
		"launcher/mod", "example.com/tgt", "/tmp/tgt",
		false, "",
		"1.24.0", replaces,
	)
	if !strings.Contains(got, "replace github.com/foo/bar => /abs/path/to/api") {
		t.Errorf("expected local replace propagated in go.mod, got:\n%s", got)
	}
}

func TestBuildLauncherGoModResolvesRelativeReplace(t *testing.T) {
	replaces := []*modfile.Replace{
		{
			Old: module.Version{Path: "github.com/foo/bar"},
			New: module.Version{Path: "../../api"},
		},
	}
	got := launcher.BuildLauncherGoModForTest(
		"launcher/mod", "example.com/tgt", "/project/tools/nleval",
		false, "",
		"1.24.0", replaces,
	)
	want := "replace github.com/foo/bar => /project/api"
	if !strings.Contains(got, want) {
		t.Errorf("expected relative path resolved to %q in go.mod, got:\n%s", want, got)
	}
}

func TestBuildLauncherGoModSkipsVersionPinnedReplace(t *testing.T) {
	replaces := []*modfile.Replace{
		{
			Old: module.Version{Path: "github.com/foo/bar", Version: "v1.0.0"},
			New: module.Version{Path: "github.com/foo/barv2", Version: "v2.0.0"},
		},
	}
	got := launcher.BuildLauncherGoModForTest(
		"launcher/mod", "example.com/tgt", "/tmp/tgt",
		false, "",
		"1.24.0", replaces,
	)
	if strings.Contains(got, "github.com/foo/barv2") {
		t.Errorf("version-pinned replace should NOT be propagated, got:\n%s", got)
	}
}

func TestReadTargetGoModReplace(t *testing.T) {
	dir := t.TempDir()
	goModContent := "module example.com/tgt\n\ngo 1.24.0\n\nrequire github.com/foo/bar v0.1.0\n\nreplace github.com/foo/bar => ../../api\n"
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(goModContent), 0o644); err != nil {
		t.Fatal(err)
	}
	goVersion, replaces := launcher.ReadTargetGoMod(dir)
	if goVersion != "1.24.0" {
		t.Errorf("go version = %q, want %q", goVersion, "1.24.0")
	}
	if len(replaces) != 1 {
		t.Fatalf("len(replaces) = %d, want 1", len(replaces))
	}
	if replaces[0].Old.Path != "github.com/foo/bar" {
		t.Errorf("replace old path = %q, want %q", replaces[0].Old.Path, "github.com/foo/bar")
	}
	if replaces[0].New.Path != "../../api" {
		t.Errorf("replace new path = %q, want %q", replaces[0].New.Path, "../../api")
	}
}
