package launcher_test

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"testing"

	"github.com/shatter-dev/shatter/shatter-go/launcher"
)

func TestGenerateLauncherMainIsDeterministic(t *testing.T) {
	importPath := "example.com/targets"
	first := launcher.GenerateLauncherMain(importPath)
	second := launcher.GenerateLauncherMain(importPath)
	if first != second {
		t.Error("GenerateLauncherMain is not deterministic")
	}
}

func TestGenerateLauncherMainHeader(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	if !strings.Contains(src, "// Code generated by Shatter. DO NOT EDIT.") {
		t.Error("missing generated-file header")
	}
	if !strings.HasPrefix(strings.TrimPrefix(src, "// Code generated by Shatter. DO NOT EDIT.\n"), "package main") {
		t.Error("first non-comment line must be 'package main'")
	}
}

func TestGenerateLauncherMainImportsTargetPackage(t *testing.T) {
	importPath := "example.com/mypkg"
	src := launcher.GenerateLauncherMain(importPath)
	if !strings.Contains(src, `"example.com/mypkg"`) {
		t.Errorf("generated source missing import %q\nsource:\n%s", importPath, src)
	}
}

func TestGenerateLauncherMainContainsWireTypes(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	for _, want := range []string{
		"launcherRequest",
		"launcherResponse",
		"target.PlanDescriptor",
		"target.ShatterInvoke",
		"ReturnValue",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestGenerateLauncherMainContainsRunLoop(t *testing.T) {
	src := launcher.GenerateLauncherMain("example.com/targets")
	for _, want := range []string{
		"bufio.NewScanner",
		"sc.Scan()",
		"json.Unmarshal",
		"enc.Encode",
		"os.Exit(1)",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source missing %q", want)
		}
	}
}

func TestGenerateLauncherMainDiffersByImportPath(t *testing.T) {
	a := launcher.GenerateLauncherMain("example.com/pkg-a")
	b := launcher.GenerateLauncherMain("example.com/pkg-b")
	if a == b {
		t.Error("different import paths should produce different sources")
	}
}

func TestBuildOptionsValidation(t *testing.T) {
	cases := []struct {
		name string
		opts launcher.BuildOptions
		want string
	}{
		{
			name: "missing hash",
			opts: launcher.BuildOptions{TargetModulePath: "x", TargetModuleDir: "/x", TargetImportPath: "x"},
			want: "DiscoveryHash",
		},
		{
			name: "missing module path",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModuleDir: "/x", TargetImportPath: "x"},
			want: "TargetModulePath",
		},
		{
			name: "missing module dir",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModulePath: "x", TargetImportPath: "x"},
			want: "TargetModuleDir",
		},
		{
			name: "missing import path",
			opts: launcher.BuildOptions{DiscoveryHash: "abc", TargetModulePath: "x", TargetModuleDir: "/x"},
			want: "TargetImportPath",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, _, err := launcher.BuildLauncher(tc.opts)
			if err == nil {
				t.Fatal("expected error, got nil")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q missing %q", err.Error(), tc.want)
			}
		})
	}
}

func TestBuildLauncherConcurrentCallsShareSingleBuild(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("fake go script uses POSIX shell")
	}

	fakeBinDir := t.TempDir()
	countDir := t.TempDir()
	fakeGo := filepath.Join(fakeBinDir, "go")
	fakeGoScript := `#!/bin/sh
set -eu
out=""
while [ "$#" -gt 0 ]; do
	if [ "$1" = "-o" ]; then
		shift
		out="$1"
	fi
	shift || true
done
if [ -z "$out" ]; then
	exit 0
fi
touch "$SHATTER_FAKE_GO_COUNT_DIR/invocation-$$"
sleep 0.2
mkdir -p "$(dirname "$out")"
printf '#!/bin/sh\nexit 0\n' > "$out"
chmod +x "$out"
`
	if err := os.WriteFile(fakeGo, []byte(fakeGoScript), 0o755); err != nil {
		t.Fatalf("write fake go: %v", err)
	}
	t.Setenv("PATH", fakeBinDir+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("SHATTER_FAKE_GO_COUNT_DIR", countDir)

	targetModuleDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(targetModuleDir, "go.mod"), []byte("module example.com/targets\n\ngo 1.23\n"), 0o644); err != nil {
		t.Fatalf("write target go.mod: %v", err)
	}

	opts := launcher.BuildOptions{
		TargetModulePath: "example.com/targets",
		TargetModuleDir:  targetModuleDir,
		TargetImportPath: "example.com/targets",
		DiscoveryHash:    "same-discovery-hash",
		GeneratedDir:     filepath.Join(t.TempDir(), "generated"),
		BinariesDir:      filepath.Join(t.TempDir(), "binaries"),
	}

	const workers = 8
	start := make(chan struct{})
	var wg sync.WaitGroup
	wg.Add(workers)
	freshResults := make(chan bool, workers)
	errs := make(chan error, workers)

	for range workers {
		go func() {
			defer wg.Done()
			<-start
			_, fresh, err := launcher.BuildLauncher(opts)
			if err != nil {
				errs <- err
				return
			}
			freshResults <- fresh
		}()
	}

	close(start)
	wg.Wait()
	close(errs)
	close(freshResults)

	for err := range errs {
		t.Errorf("BuildLauncher returned error: %v", err)
	}
	if t.Failed() {
		return
	}

	markers, err := os.ReadDir(countDir)
	if err != nil {
		t.Fatalf("read fake go markers: %v", err)
	}
	if len(markers) != 1 {
		t.Fatalf("go build invocations = %d, want 1", len(markers))
	}

	freshCount := 0
	for fresh := range freshResults {
		if fresh {
			freshCount++
		}
	}
	if freshCount != 1 {
		t.Fatalf("fresh builds = %d, want 1", freshCount)
	}
}
